[profile.default]
src = "src"
out = "out"
lib = ["lib"]
via_ir = true
optimizer_runs = 100
remappings = [
    'ds-test/ = lib/forge-std/lib/ds-test/src/',
    'forge-std/ = lib/forge-std/src/',
    'openzeppelin-contracts/ = @openzeppelin/'
]

[invariant]
runs = 256
depth = 1000
fail_on_revert = true

# [coverage]
# via_ir = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
